import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
// import PhaserGame from '../compnents/phaserGame';
// import  '../compnents/phaserGame';
// import dynamic from 'next/dynamic'

// const DynamicComponentWithNoSSR = dynamic(
//   () => import('../components/phaserGame'),
//   { ssr: false }
// )

const Home: NextPage = () => {

  // const [loading, setLoading] = useState(false);

  // useEffect(() => {
  //   setLoading(true)
  // }, []);
  return (
    <div className={styles.containerBox}>
      <Head>
        <title>Hackmon</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
      </main>
      {/* <div id="hackmon-game"> */}
        {/* <PhaserGame /> */}
      {/* </div> */}
      {/* {loading ? <DynamicComponentWithNoSSR /> : null} */}
      {/* <DynamicComponentWithNoSSR />  */}

      
    </div>
  );
};

export default Home;
